server:
  port: 8080
  compression:
    # Enable response compression
    enabled: true
    # The comma-separated list of mime types that should be compressed
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    # Compress the response only if the response size is at least 1KB
    min-response-size: 1024

# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/socialnetwork
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.MySQL55Dialect
        # Hibernate Search properties
        search:
          default:
            directory_provider: filesystem
            indexBase: ./search-index

# Expose all Actuator endpoints
management:
  endpoints:
    web:
     exposure:
      include: "*"

app:
  # This is not supposed to be here...
  jwtSecret: kaYy33CE0CWI9b9yNsh0W3N3Ce6ndYIZrE-yzQzAEplvSftXI5FdZvTfLT2w6YlOWYpn-Dnh5akS5kMjd1wUeQ
  jwtExpirationInMs: 604800000